# .github/workflows/build.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Building
      - name: Build the app
        run: ./gradlew build

      # Linting
      - name: Run linter
        run: ./gradlew lint

      # Testing
      - name: Run tests
        run: ./gradlew test